### ISSUE TITLE
Can't compile with last version of Xcode

### ISSUE THREAD

**Issue by SObS** [freerunnering/HomeKitBridge#3]
Anybody success?

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_HAKBrightnessCharacteristic", referenced from:
      objc-class-ref in HKBLightAccessory.o
```

**Comment by freerunnering** [comment]
To quote the [readme](https://github.com/freerunnering/HomeKitBridge#building):
>Make sure you have the HomeKit Accessory Simulator installed in "/Applications" The project reaches inside it and grabs the private framework as it builds.

>The easiest way to get the HomeKit simulator is to go in Xcode to the menu bar > Xcode > Open Developer Tool > More Developer Tools... > And then download "Hardware tools for Xcode 6.1".
