### ISSUE TITLE
Property access is using 'setDelegate:' method which is unavailable

### ISSUE THREAD

**Issue by suhajdab** [freerunnering/HomeKitBridge#4]
When trying to build I get the following problem:

.../HomeKitBridge/HomeKitBridge/LIFX/HKBLightAccessoryLIFX.m:46:8: Property access is using 'setDelegate:' method which is unavailable

.../HomeKitBridge/HomeKitBridge/LIFX/HKBLightAccessoryLIFX.h:28:1: 'setDelegate:' has been explicitly marked unavailable here

**Comment by freerunnering** [comment]
Fixed: Grab the latest code and the latest Accessory Simulator and it should work now.
